In [20]:
import pandas as pd
from itertools import chain
from collections import Counter

In [24]:
df_fullset = pd.read_csv(
    "/net/pc230050/nobackup/users/duinen/04_weather_year_selection/outputs/simulated_annealing/run_NL_20251024_1320/results_grid.csv",
    index_col=0,
)
df_subset = pd.read_csv(
    "/net/pc230050/nobackup/users/duinen/04_weather_year_selection/outputs/simulated_annealing/subsampling/NL_20251024_1320_5y_subset/results_grid.csv",
    index_col=0,
)

In [29]:
def count_duplicates(df: pd.DataFrame) -> Counter:
    """Count duplicate modelyears in the selected years column."""
    lists = df["selected"].apply(eval)
    model_years_flat = list(chain.from_iterable(lists))
    return Counter(model_years_flat)

In [32]:
counts_full = count_duplicates(df_fullset)
counts_sub = count_duplicates(df_subset)

In [60]:
# Calculate fraction of model_years in subset vs full
idx = sorted(counts_full.keys())
full = pd.Series({k: counts_full[k] for k in idx}, name="full")
sub = pd.Series({k: counts_sub[k] for k in idx}, name="subset")
df_counts = pd.concat([full, sub], axis=1)
df_counts["fraction"] = df_counts["subset"] / df_counts["full"]

In [61]:
df_counts.sort_values("full", ascending=False)

                    full  subset  fraction
awi_cm_1_1_mr 2034    17       3  0.176471
mpi_esm1_2_hr 2033    14       3  0.214286
cmcc_cm2_sr5  2019    13       0  0.000000
ec_earth3     2043    13       2  0.153846
mri_esm2_0    2017    13       2  0.153846
...                  ...     ...       ...
bcc_csm2_mr   2021     4       1  0.250000
awi_cm_1_1_mr 2016     4       1  0.250000
bcc_csm2_mr   2020     3       0  0.000000
awi_cm_1_1_mr 2041     2       1  0.500000
ec_earth3     2024     1       0  0.000000

[174 rows x 3 columns]

In [52]:
df_counts.sort_values("fraction", ascending=False)

                    full  subset  fraction
cmcc_cm2_sr5  2020     5       4       0.8
mpi_esm1_2_hr 2021    10       5       0.5
mri_esm2_0    2040     4       2       0.5
cmcc_cm2_sr5  2032     6       3       0.5
awi_cm_1_1_mr 2041     2       1       0.5
...                  ...     ...       ...
ec_earth3     2018     8       0       0.0
bcc_csm2_mr   2030     6       0       0.0
mpi_esm1_2_hr 2035    10       0       0.0
              2036    10       0       0.0
ec_earth3     2015     8       0       0.0

[174 rows x 3 columns]

In [53]:
df_counts.sort_values("subset", ascending=False)

                    full  subset  fraction
awi_cm_1_1_mr 2020    12       5  0.416667
mpi_esm1_2_hr 2021    10       5  0.500000
bcc_csm2_mr   2019    10       5  0.500000
mpi_esm1_2_hr 2034    10       4  0.400000
ec_earth3     2023    12       4  0.333333
...                  ...     ...       ...
              2018     8       0  0.000000
mpi_esm1_2_hr 2035    10       0  0.000000
              2036    10       0  0.000000
bcc_csm2_mr   2030     6       0  0.000000
ec_earth3     2015     8       0  0.000000

[174 rows x 3 columns]